
-- Users are managed by Supabase Auth (auth.users)
-- We need a public profiles table to store roles

create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  role text check (role in ('student', 'admin')) default 'student'
);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;

-- Policies for profiles
create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );
  
-- Trigger to create profile on signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, role)
  values (new.id, new.email, 'student');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Complaints table
create table public.complaints (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  description text not null,
  hostel text not null,
  block text,
  category text,
  status text default 'Pending',
  urgency_score int,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.complaints enable row level security;

-- Policies for complaints
create policy "Students can view their own complaints."
  on complaints for select
  using ( auth.uid() = user_id );

create policy "Admins can view all complaints."
  on complaints for select
  using ( 
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

create policy "Students can create complaints."
  on complaints for insert
  with check ( auth.uid() = user_id );

create policy "Admins can update complaints."
  on complaints for update
  using ( 
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );
